### ISSUE TITLE
Circular dependency issue in Linux install

### ISSUE THREAD

**Issue by eafpres** [j3soon/tbparse#6]
It appears there are some dependency issues with this release:
```
ERROR: black 21.11b1 has requirement typing-extensions>=3.10.0.0, but you'll have typing-extensions 3.7.4.3 which is incompatible.
ERROR: pylint 2.12.2 has requirement typing-extensions>=3.10.0; python_version < "3.10", but you'll have typing-extensions 3.7.4.3 which is incompatible.
ERROR: astroid 2.9.0 has requirement typing-extensions>=3.10; python_version < "3.10", but you'll have typing-extensions 3.7.4.3 which is incompatible.
```
This then messed up using my ide:
```
Traceback (most recent call last):
  File "/home/eafpres/.local/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/app/start.py", line 236, in main
    mainwindow.main(options, args)
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2035, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 848, in setup
    internal_plugins = find_internal_plugins()
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/app/find_plugins.py", line 92, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/plugins/pylint/plugin.py", line 25, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/plugins/pylint/main_widget.py", line 35, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "/home/eafpres/.local/lib/python3.8/site-packages/spyder/plugins/pylint/utils.py", line 16, in <module>
    import pylint.config
  File "/home/eafpres/.local/lib/python3.8/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/home/eafpres/.local/lib/python3.8/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/home/eafpres/.local/lib/python3.8/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/home/eafpres/.local/lib/python3.8/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/home/eafpres/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/home/eafpres/.local/lib/python3.8/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/home/eafpres/.local/lib/python3.8/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/home/eafpres/.local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 47, in <module>
    from astroid import decorators, mixins, util
  File "/home/eafpres/.local/lib/python3.8/site-packages/astroid/decorators.py", line 36, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/home/eafpres/.local/lib/python3.8/site-packages/typing_extensions.py)
```
I'm running Ubuntu 20.04 inside of WSLg under Windows 11

**Comment by j3soon** [comment]
tbparse only requires `typing-extensions>=3.6.6`, so I'm not sure why pip downgrades the `typing_extension` package from `3.10.0.0` to `3.7.4.3`. I tried to reproduce this issue on Ubuntu 20.04 (as mentioned in [your Reddit thread](https://www.reddit.com/r/MachineLearning/comments/svnep5/p_tbparse_load_tensorboard_event_logs_as_pandas/hxi1ixt/)), but didn't observe such behavior.

If someone encounters the same issue, creating a new virtual environment may solve the problem. Alternatively, you can use `pip install typing_extensions==3.10` as mentioned by @eafpres in the Reddit thread.
